import '../globals.css';
import { AuthProvider } from "@/utils/AuthProvider";


export const metadata = {
  title: 'Wild and Free : Auth',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}